import type { NavItem, ProductRecord, QueueTask } from './types'

export const navItems: NavItem[] = [
  { id: 'today', label: '今日工作台', hint: 'Overview' },
  { id: 'product', label: '产品库', hint: 'Products', badge: '24' },
  { id: 'queue', label: '提审队列', hint: 'Submission', badge: '3' },
]

export const queueTasks: QueueTask[] = [
  {
    id: 'task-1',
    sku: 'SKU00044974',
    title: '焕亮修护精华套装',
    category: '图包表格',
    progress: 78,
    status: 'running',
    detail: '正在匹配产品参数图与详情图',
    eta: '约 2 分钟',
  },
  {
    id: 'task-2',
    sku: 'SKU00044721',
    title: '柔润护手霜礼盒',
    category: '英文参数图',
    progress: 100,
    status: 'ready',
    detail: '资产已生成，等待提审',
  },
  {
    id: 'task-3',
    sku: 'SKU00044518',
    title: '便携式积木拼图',
    category: '产品资料',
    progress: 46,
    status: 'attention',
    detail: '缺少一张透明底产品图',
  },
]

export const products: ProductRecord[] = [
  {
    sku: 'SKU00044974',
    title: '焕亮修护精华套装',
    brand: 'Westmonth',
    category: '护肤系列',
    updated: '12 分钟前',
    completion: 92,
    assetCount: 8,
    status: 'ready',
    variant: 'lavender',
    mediaSize: 'tall',
    pinned: true,
  },
  {
    sku: 'SKU00044721',
    title: '柔润护手霜礼盒',
    brand: 'Morrow',
    category: '身体护理',
    updated: '28 分钟前',
    completion: 100,
    assetCount: 10,
    status: 'ready',
    variant: 'peach',
    mediaSize: 'medium',
  },
  {
    sku: 'SKU00044518',
    title: '便携式积木拼图',
    brand: 'Playform',
    category: '儿童玩具',
    updated: '46 分钟前',
    completion: 64,
    assetCount: 5,
    status: 'attention',
    variant: 'mint',
    mediaSize: 'short',
  },
  {
    sku: 'SKU00044602',
    title: '柔雾保湿气垫',
    brand: 'Westmonth',
    category: '彩妆系列',
    updated: '1 小时前',
    completion: 86,
    assetCount: 7,
    status: 'running',
    variant: 'lavender',
    mediaSize: 'medium',
  },
  {
    sku: 'SKU00044573',
    title: '晨光香氛沐浴露',
    brand: 'Aureline',
    category: '身体护理',
    updated: '2 小时前',
    completion: 78,
    assetCount: 6,
    status: 'running',
    variant: 'peach',
    mediaSize: 'tall',
  },
  {
    sku: 'SKU00044460',
    title: '微光护唇精华',
    brand: 'Morrow',
    category: '彩妆系列',
    updated: '3 小时前',
    completion: 100,
    assetCount: 9,
    status: 'ready',
    variant: 'mint',
    mediaSize: 'short',
  },
  {
    sku: 'SKU00044328',
    title: '深层净澈洁面乳',
    brand: 'Westmonth',
    category: '护肤系列',
    updated: '昨天',
    completion: 96,
    assetCount: 8,
    status: 'ready',
    variant: 'lavender',
    mediaSize: 'medium',
  },
  {
    sku: 'SKU00044295',
    title: '轻盈随行水杯',
    brand: 'Everyday Lab',
    category: '生活方式',
    updated: '昨天',
    completion: 72,
    assetCount: 4,
    status: 'attention',
    variant: 'mint',
    mediaSize: 'tall',
  },
  {
    sku: 'SKU00044187',
    title: '云朵软绒睡眠眼罩',
    brand: 'Luma Home',
    category: '家居用品',
    updated: '2 天前',
    completion: 88,
    assetCount: 6,
    status: 'ready',
    variant: 'peach',
    mediaSize: 'short',
  },
  {
    sku: 'SKU00044056',
    title: '儿童拼装工程车',
    brand: 'Playform',
    category: '儿童玩具',
    updated: '2 天前',
    completion: 58,
    assetCount: 4,
    status: 'attention',
    variant: 'lavender',
    mediaSize: 'medium',
  },
  {
    sku: 'SKU00043978',
    title: '清透防晒乳',
    brand: 'Aureline',
    category: '护肤系列',
    updated: '3 天前',
    completion: 94,
    assetCount: 8,
    status: 'ready',
    variant: 'mint',
    mediaSize: 'short',
  },
  {
    sku: 'SKU00043864',
    title: '旅行收纳化妆包',
    brand: 'Luma Home',
    category: '生活方式',
    updated: '3 天前',
    completion: 81,
    assetCount: 6,
    status: 'running',
    variant: 'peach',
    mediaSize: 'tall',
  },
]

export const activityItems = [
  { time: '09:42', title: '完成 SKU00044721 的参数图', meta: '自动生成 · 英文版', tone: 'success' },
  { time: '09:18', title: '同步 12 个已定稿 SKU', meta: '来自云备份 · 2 分钟前', tone: 'neutral' },
  { time: '08:56', title: '发现 3 个待处理任务', meta: '提审队列 · 需要关注', tone: 'warning' },
]

export const productMetrics = [
  { label: '待处理 SKU', value: '24', delta: '+6', note: '较昨日' },
  { label: '本周已完成', value: '86', delta: '+18%', note: '完成率提升' },
  { label: '素材完整度', value: '92%', delta: '+4.2%', note: '近 7 日' },
]
