// Generated cloud-backed ingredient template loader. Do not edit this file by hand.
  const PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_KEY = 'plm-floating-helper:product-development-ingredient-templates:v1';
  const PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_SCHEMA = 1;
  const PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_EMPTY = Object.freeze([]);
  let productDevelopmentIngredientTemplatesRemoteCache = loadProductDevelopmentIngredientTemplatesCache();
  let productDevelopmentIngredientTemplatesLoadPromise = null;
  let productDevelopmentIngredientTemplatesRemoteCheckedAt = 0;

  function normalizeProductDevelopmentIngredientTemplates(value) {
    const list = Array.isArray(value) ? value : value && Array.isArray(value.templates) ? value.templates : [];
    return list.filter((item) => item && String(item.id || '').trim() && (String(item.kind || '').trim().toLowerCase() === 'human' || String(item.kind || '').trim().toLowerCase() === 'pet') && Array.isArray(item.sheets) && item.sheets.some((sheet) => sheet && String(sheet.name || '').trim() && Array.isArray(sheet.cells) && sheet.cells.length));
  }

  function loadProductDevelopmentIngredientTemplatesCache() {
    try {
      const stored = typeof GM_getValue === 'function'
        ? GM_getValue(PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_KEY, null)
        : (typeof localStorage !== 'undefined' ? JSON.parse(localStorage.getItem(PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_KEY) || 'null') : null);
      const value = typeof stored === 'string' ? JSON.parse(stored) : stored;
      const templates = value && Number(value.schemaVersion) === PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_SCHEMA
        ? normalizeProductDevelopmentIngredientTemplates(value.templates)
        : [];
      return templates.length ? { ...value, templates: Object.freeze(templates) } : null;
    } catch (_) {
      return null;
    }
  }

  function saveProductDevelopmentIngredientTemplatesCache(value) {
    try {
      if (typeof GM_setValue === 'function') GM_setValue(PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_KEY, value);
      else if (typeof localStorage !== 'undefined') localStorage.setItem(PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_KEY, JSON.stringify(value));
    } catch (_) {
      // A cache write failure must not prevent the cloud asset from being used.
    }
  }

  function productDevelopmentIngredientTemplatesData() {
    return productDevelopmentIngredientTemplatesRemoteCache
      ? productDevelopmentIngredientTemplatesRemoteCache.templates
      : PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_EMPTY;
  }

  async function ensureProductDevelopmentIngredientTemplatesLoaded(force) {
    if (productDevelopmentIngredientTemplatesLoadPromise) return productDevelopmentIngredientTemplatesLoadPromise;
    const cached = productDevelopmentIngredientTemplatesRemoteCache;
    const cachedTemplates = cached && Array.isArray(cached.templates) ? cached.templates : PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_EMPTY;
    if (!force && cachedTemplates.length && productDevelopmentIngredientTemplatesRemoteCheckedAt && Date.now() - productDevelopmentIngredientTemplatesRemoteCheckedAt < 24 * 60 * 60 * 1000) return cachedTemplates;
    productDevelopmentIngredientTemplatesLoadPromise = (async () => {
      try {
        if (typeof cloudAssetRequest !== 'function' || typeof fetchCloudAsset !== 'function') throw new Error('云端成分表模板加载器不可用');
        const manifest = await cloudAssetRequest('/assets/manifest.json', 'json');
        const descriptor = manifest && manifest.assets && manifest.assets.ingredientTemplates;
        if (!descriptor || !descriptor.path) throw new Error('云端尚未发布成分表模板');
        const descriptorHash = String(descriptor.sha256 || '').toLowerCase();
        if (!force && cachedTemplates.length && descriptorHash && String(cached.assetHash || '').toLowerCase() === descriptorHash) {
          productDevelopmentIngredientTemplatesRemoteCheckedAt = Date.now();
          return cachedTemplates;
        }
        const text = await fetchCloudAsset(descriptor, 'text');
        const payload = JSON.parse(text || '{}');
        if (!payload || Number(payload.schemaVersion) !== PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_SCHEMA) throw new Error('云端成分表模板格式无效');
        const templates = normalizeProductDevelopmentIngredientTemplates(payload.templates);
        if (!templates.length) throw new Error('云端成分表模板为空');
        const next = {
          schemaVersion: PRODUCT_DEVELOPMENT_INGREDIENT_TEMPLATES_CACHE_SCHEMA,
          dataVersion: String(manifest.dataVersion || ''),
          assetPath: String(descriptor.path || ''),
          assetHash: descriptorHash,
          updatedAt: new Date().toISOString(),
          templates: Object.freeze(templates),
        };
        saveProductDevelopmentIngredientTemplatesCache(next);
        productDevelopmentIngredientTemplatesRemoteCache = next;
        productDevelopmentIngredientTemplatesRemoteCheckedAt = Date.now();
        return next.templates;
      } catch (error) {
        if (cachedTemplates.length) {
          productDevelopmentIngredientTemplatesRemoteCheckedAt = Date.now();
          console.warn('PLM ingredient templates cloud refresh failed; using local cache:', error);
          return cachedTemplates;
        }
        throw error;
      }
    })().finally(() => {
      productDevelopmentIngredientTemplatesLoadPromise = null;
    });
    return productDevelopmentIngredientTemplatesLoadPromise;
  }
